version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kampuspu_rt
      MYSQL_USER: kampuspu_rt
      MYSQL_PASSWORD: dhM3YMtk%ADD]Za-
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./kampuspu_apirt06.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  php:
    image: ghcr.io/danprat/fandi-flask-app/php:latest
    container_name: php_app
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - ./uploads:/var/www/html/uploads
    networks:
      - app_network

  flask:
    image: ghcr.io/danprat/fandi-flask-app/flask:latest
    container_name: flask_app
    ports:
      - "5000:5000"
    networks:
      - app_network

  python:
    image: ghcr.io/danprat/fandi-flask-app/python:latest
    container_name: python_scripts
    volumes:
      - ./uploads:/app/uploads
      - ./python_scripts:/app
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge